{
	"TracRTC__Realtime_Clean_Settings__c": {
	"records": [
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Settings__c",
				"referenceId": "TracRTC__Realtime_Clean_Settings__cRef1"
			},
			"TracRTC__Assign_Lead_to_Account_Owner__c": false,
			"TracRTC__Assign_Lead_to_Lead_Owner__c": false,
			"TracRTC__Company_Match_Type__c": "dnb",
			"TracRTC__DDC_Match__c": true,
			"TracRTC__Disable_DnB_Company_Record_Insertion__c": false,
			"TracRTC__Disable_Trigger__c": false,
			"TracRTC__DUNSRight_Confidence_Code__c": "5",
			"TracRTC__Enable_Duplicate_Record_Display__c": true,
			"TracRTC__Enable_Logging__c": true,
			"TracRTC__Infer_Website_from_Email_Domain__c": true,
			"TracRTC__Internal_Record_Match__c": true,
			"TracRTC__Match_Domestic_Company__c": true,
			"TracRTC__Match_Global_Company__c": true,
			"TracRTC__Match_Parent_Company__c": true,
			"TracRTC__Match_to_Headquarters__c": true,
			"TracRTC__OAuth_Secret__c": "1358209318762686195",
			"TracRTC__Password__c": "E!1383fb52Y8SXQn6HZkLylqOpcbUd939wz",
			"TracRTC__Re_run_assignment_rules_after_clean__c": false,
			"TracRTC__Round_Robin_Lead_Assignment__c": true,
			"TracRTC__Select_Company_Match__c": true,
			"TracRTC__Username__c": "gadamson@realtimeleadclean.app"
		}
	]
},
	"TracRTC__Realtime_Clean_Field_Setting__c": {
	"records": [
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef5"
			},
			"Name": "DomesticStreet"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef6"
			},
			"Name": "DomesticCity"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef7"
			},
			"Name": "GlobalCity"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef8"
			},
			"Name": "GlobalState"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef9"
			},
			"Name": "GlobalCountry",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "global_ultimate_parent_country__c"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef10"
			},
			"Name": "GlobalPostalCode"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef11"
			},
			"Name": "GlobalPhone"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef12"
			},
			"Name": "GlobalFax"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef13"
			},
			"Name": "DomesticState"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef15"
			},
			"Name": "DomesticPostalCode"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef16"
			},
			"Name": "DomesticPhone"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef17"
			},
			"Name": "DomesticFax"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef20"
			},
			"Name": "DomesticDescription"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef21"
			},
			"Name": "GlobalDescription"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef22"
			},
			"Name": "GlobalNumberOfEmployees"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef24"
			},
			"Name": "DomesticIndustry"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef25"
			},
			"Name": "DomesticWebsite"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef26"
			},
			"Name": "GlobalIndustry"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef27"
			},
			"Name": "GlobalWebsite"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef34"
			},
			"Name": "GlobalCompanyDunsNumber"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef36"
			},
			"Name": "GlobalStreet"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef47"
			},
			"Name": "ParentPostalCode",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "parent_zip__c"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef48"
			},
			"Name": "ParentPhone"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef49"
			},
			"Name": "ParentFax"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef50"
			},
			"Name": "ParentDescription"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef52"
			},
			"Name": "ParentIndustry"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef54"
			},
			"Name": "ParentWebsite"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef58"
			},
			"Name": "FirstName",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "firstname"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef59"
			},
			"Name": "LastName",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "lastname"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef60"
			},
			"Name": "Company",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "company",
			"TracRTC__Match_Precedence__c": "company"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef61"
			},
			"Name": "Email",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "email"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef62"
			},
			"Name": "Title",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "title"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef63"
			},
			"Name": "Street",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "street",
			"TracRTC__Match_Precedence__c": "contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef64"
			},
			"Name": "City",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "city",
			"TracRTC__Match_Precedence__c": "contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef65"
			},
			"Name": "State",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "",
			"TracRTC__Match_Precedence__c": "contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef66"
			},
			"Name": "Country",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "",
			"TracRTC__Match_Precedence__c": "contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef67"
			},
			"Name": "PostalCode",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "postalcode",
			"TracRTC__Match_Precedence__c": "contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef68"
			},
			"Name": "Phone",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "phone",
			"TracRTC__Match_Precedence__c": "contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef69"
			},
			"Name": "Fax",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "fax"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef70"
			},
			"Name": "AnnualRevenue",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "annualrevenue"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef71"
			},
			"Name": "Description",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "description"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef72"
			},
			"Name": "NumberOfEmployees",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "numberofemployees"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef73"
			},
			"Name": "Industry",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "industry"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef74"
			},
			"Name": "Website",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Field__c": "website"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef75"
			},
			"Name": "NaicsCode__c",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "naicscode__c"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef76"
			},
			"Name": "NaicsDesc__c",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "naicsdesc__c"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef77"
			},
			"Name": "SicCode__c",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "siccode__c"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef78"
			},
			"Name": "SicDesc__c",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "sicdesc__c"
		},
		{
			"attributes": {
				"type": "TracRTC__Realtime_Clean_Field_Setting__c",
				"referenceId": "TracRTC__Realtime_Clean_Field_Setting__cRef79"
			},
			"Name": "DAndBCompany",
			"TracRTC__Append_Settings__c": "always",
			"TracRTC__Field__c": "dandbcompanyid"
		}
	]
},
	"TracRTC__Enabled_Duplicate_Rules__c": {
	"records": [
		{
			"attributes": {
				"type": "TracRTC__Enabled_Duplicate_Rules__c",
				"referenceId": "TracRTC__Enabled_Duplicate_Rules__cRef1"
			},
			"Name": "0Bm1N000000MIa7SAG",
			"TracRTC__Duplicate_Rule_Name__c": "Fuzzy_Match_to_Account",
			"TracRTC__Duplicate_Rule_Rank__c": "4",
			"TracRTC__Match_Rule_Object_Names__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Enabled_Duplicate_Rules__c",
				"referenceId": "TracRTC__Enabled_Duplicate_Rules__cRef2"
			},
			"Name": "0Bm1N000000MIaCSAW",
			"TracRTC__Duplicate_Rule_Name__c": "Standard_Lead_to_Account_Match",
			"TracRTC__Duplicate_Rule_Rank__c": "3",
			"TracRTC__Match_Rule_Object_Names__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Enabled_Duplicate_Rules__c",
				"referenceId": "TracRTC__Enabled_Duplicate_Rules__cRef3"
			},
			"Name": "0Bm1N000000MIaMSAW",
			"TracRTC__Duplicate_Rule_Name__c": "Standard_Lead_to_Contact_Match",
			"TracRTC__Duplicate_Rule_Rank__c": "1",
			"TracRTC__Match_Rule_Object_Names__c": "Contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Enabled_Duplicate_Rules__c",
				"referenceId": "TracRTC__Enabled_Duplicate_Rules__cRef4"
			},
			"Name": "0Bm1N000000MIa2SAG",
			"TracRTC__Duplicate_Rule_Name__c": "Strict_Match_to_Account",
			"TracRTC__Duplicate_Rule_Rank__c": "2",
			"TracRTC__Match_Rule_Object_Names__c": "Account"
		}
	]
},
	"TracRTC__Match_Resolution_Engine__c": {
	"records": [
		{
			"attributes": {
				"type": "TracRTC__Match_Resolution_Engine__c",
				"referenceId": "TracRTC__Match_Resolution_Engine__cRef1"
			},
			"TracRTC__Final_Tie_Break_Setting__c": "CreatedDate ASC",
			"TracRTC__First_Filter_Rank__c": "Type---equals---Customer",
			"TracRTC__Second_Filter_Rank__c": "AnnualRevenue---isnotblank"
		}
	]
},
    "TracRTC__Match_Resolution_Engine_2__c": {
    "records": [
        {
            "attributes": {
                "type": "TracRTC__Match_Resolution_Engine_2__c",
                "referenceId": "TracRTC__Match_Resolution_Engine_2__cRef1"
            },
            "TracRTC__Final_Tie_Break__c": "CreatedDate ASC",
            "TracRTC__First_Filter_Rank__c": "Type---equals---Customer",
            "TracRTC__Second_Filter_Rank__c": "AnnualRevenue---isnotblank",
            "Name": "Account",
            "TracRTC__SObjectName__c": "Account"
        },
        {
            "attributes": {
                "type": "TracRTC__Match_Resolution_Engine_2__c",
                "referenceId": "TracRTC__Match_Resolution_Engine_2__cRef2"
            },
            "TracRTC__Final_Tie_Break__c": "CreatedDate ASC",
            "Name": "Contact",
            "TracRTC__SObjectName__c": "Contact"
        },
        {
            "attributes": {
                "type": "TracRTC__Match_Resolution_Engine_2__c",
                "referenceId": "TracRTC__Match_Resolution_Engine_2__cRef3"
            },
            "TracRTC__Final_Tie_Break__c": "CreatedDate ASC",
            "Name": "Lead",
            "TracRTC__SObjectName__c": "Lead"
        }
    ]
},
    "TracRTC__Multiple_Field_Match__c": {
	"records": [
        {
            "attributes": {
                "type": "TracRTC__Multiple_Field_Match__c",
                "referenceId": "TracRTC__Multiple_Field_Match__cRef1"
            },
            "Name": "TracRTC__Traction_Complete_Domain__c",
            "TracRTC__From_Field__c": "TracRTC__Traction_Complete_Domain__c",
            "TracRTC__From_SObject__c": "Lead",
            "TracRTC__To_Field__c": "TracRTC__Traction_Complete_Domain__c",
            "TracRTC__To_SObject__c": "Lead"
        },
        {
            "attributes": {
                "type": "TracRTC__Multiple_Field_Match__c",
                "referenceId": "TracRTC__Multiple_Field_Match__cRef2"
            },
            "Name": "Phone",
            "TracRTC__From_Field__c": "Phone",
            "TracRTC__From_SObject__c": "Lead",
            "TracRTC__To_Field__c": "Phone",
            "TracRTC__To_SObject__c": "Lead"
        },
        {
            "attributes": {
                "type": "TracRTC__Multiple_Field_Match__c",
                "referenceId": "TracRTC__Multiple_Field_Match__cRef3"
            },
            "Name": "Company",
            "TracRTC__From_Field__c": "Company",
            "TracRTC__From_SObject__c": "Lead",
            "TracRTC__To_Field__c": "Company",
            "TracRTC__To_SObject__c": "Lead"
        }
    ]
},
	"TracRTC__Duplicate_Rules_Field_Setting__c": {
	"records": [
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef2"
			},
			"Name": "AnnualRevenueAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "AnnualRevenue",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "AnnualRevenue",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef3"
			},
			"Name": "CityAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "City",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "BillingCity",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef4"
			},
			"Name": "CountryAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "Country",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "BillingCountry",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef5"
			},
			"Name": "StateAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "State",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "BillingState",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef6"
			},
			"Name": "StreetAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "Street",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "BillingStreet",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef7"
			},
			"Name": "PostalCodeAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "PostalCode",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "BillingPostalCode",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef8"
			},
			"Name": "NumberOfEmployeesAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "NumberOfEmployees",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "NumberOfEmployees",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef9"
			},
			"Name": "CompanyAccount",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "Company",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "Name",
			"TracRTC__Source_SObject__c": "Account"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef10"
			},
			"Name": "TitleContact",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "Title",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "Title",
			"TracRTC__Source_SObject__c": "Contact"
		},
		{
			"attributes": {
				"type": "TracRTC__Duplicate_Rules_Field_Setting__c",
				"referenceId": "TracRTC__Duplicate_Rules_Field_Setting__cRef11"
			},
			"Name": "MobilePhoneContact",
			"TracRTC__Append_Settings__c": "blank",
			"TracRTC__Destination_Field__c": "MobilePhone",
			"TracRTC__Display_Match_Precedence__c": false,
			"TracRTC__Source_Field__c": "MobilePhone",
			"TracRTC__Source_SObject__c": "Contact"
		}
	]
},
	"TracRTC__Flow_Step__c": {
	"records": [
        {
            "attributes": {
                "type": "TracRTC__Flow_Step__c",
                "referenceId": "TracRTC__Flow_Step__cRef1"
            },
            "Name": "Convert Leads",
            "TracRTC__Data__c": "{\"stepName\":\"Convert Leads\",\"hasEmailCheckbox\":true,\"sendEmailNotification\":false,\"stepId\":null,\"startOfTimePeriod\":null,\"sortCriteriaAura\":null,\"sortCriteria\":[],\"ruleCriteriaAura\":null,\"ruleCriteria\":[{\"userEnteredValue\":\"Convert Test\",\"selectedSObjectField\":\"Email\",\"selectedSObject\":\"Lead\",\"selectedOperator\":\"equals\",\"currentDate\":null,\"comparison\":\"EQUALS\"}],\"rrItems\":null,\"originalNumberOfDaysInTimePeriod\":null,\"numberOfDaysInTimePeriod\":null,\"nextUserName\":null,\"lastUserName\":null,\"lastRRItemId\":null,\"lastRRIndex\":null,\"endOfTimePeriod\":null}"
        },
        {
            "attributes": {
                "type": "TracRTC__Flow_Step__c",
                "referenceId": "TracRTC__Flow_Step__cRef2"
            },
            "Name": "Account Based Assignment",
            "TracRTC__Data__c": "{\"stepName\":\"Account Based Assignment\",\"hasEmailCheckbox\":true,\"sendEmailNotification\":false,\"stepId\":null,\"startOfTimePeriod\":null,\"sortCriteriaAura\":null,\"sortCriteria\":[],\"ruleCriteriaAura\":null,\"ruleCriteria\":[{\"userEnteredValue\":\"Account Test\",\"selectedSObjectField\":\"Email\",\"selectedSObject\":\"Lead\",\"selectedOperator\":\"isnotblank\",\"currentDate\":null,\"comparison\":\"NOT_BLANK\"}],\"rrItems\":null,\"originalNumberOfDaysInTimePeriod\":null,\"numberOfDaysInTimePeriod\":null,\"nextUserName\":null,\"lastUserName\":null,\"lastRRItemId\":null,\"lastRRIndex\":null,\"endOfTimePeriod\":null}"
        },
        {
            "attributes": {
                "type": "TracRTC__Flow_Step__c",
                "referenceId": "TracRTC__Flow_Step__cRef3"
            },
            "Name": "Assign Matched Lead Owner",
            "TracRTC__Data__c": "{\"stepName\":\"Assign Matched Lead Owner\",\"hasEmailCheckbox\":true,\"sendEmailNotification\":false,\"stepId\":null,\"startOfTimePeriod\":null,\"sortCriteriaAura\":null,\"sortCriteria\":[{\"userEnteredValue\":\"\",\"selectedSObjectField\":\"CreatedDate\",\"selectedSObject\":\"Lead\",\"selectedOperator\":\"oldest\",\"currentDate\":\"2017-11-08\",\"comparison\":\"MIN\"}],\"ruleCriteriaAura\":null,\"ruleCriteria\":[{\"userEnteredValue\":\"Lead Match\",\"selectedSObjectField\":\"TracRTC__Traction_Complete_Status_Text__c\",\"selectedSObject\":\"Lead\",\"selectedOperator\":\"equals\",\"currentDate\":null,\"comparison\":\"EQUALS\"}],\"rrItems\":null,\"originalNumberOfDaysInTimePeriod\":null,\"numberOfDaysInTimePeriod\":null,\"nextUserName\":null,\"lastUserName\":null,\"lastRRItemId\":null,\"lastRRIndex\":null,\"endOfTimePeriod\":null}"
        },
        {
            "attributes": {
                "type": "TracRTC__Flow_Step__c",
                "referenceId": "TracRTC__Flow_Step__cRef4"
            },
            "Name": "Assign Round Robin",
            "TracRTC__Data__c": "{\"stepName\":\"Assign Round Robin\",\"hasEmailCheckbox\":true,\"sendEmailNotification\":false,\"stepId\":null,\"startOfTimePeriod\":\"2017-11-08T18:25:47.976Z\",\"sortCriteriaAura\":null,\"sortCriteria\":[],\"ruleCriteriaAura\":null,\"ruleCriteria\":[{\"userEnteredValue\":\"Guest Test\",\"selectedSObjectField\":\"Email\",\"selectedSObject\":\"Lead\",\"selectedOperator\":\"equals\",\"currentDate\":null,\"comparison\":\"EQUALS\"}],\"rrItems\":[],\"originalNumberOfDaysInTimePeriod\":7,\"numberOfDaysInTimePeriod\":7,\"nextUserName\":null,\"lastUserName\":null,\"lastRRItemId\":null,\"lastRRIndex\":null,\"endOfTimePeriod\":\"2017-11-15T18:25:47.976Z\"}"
        },
        {
            "attributes": {
                "type": "TracRTC__Flow_Step__c",
                "referenceId": "TracRTC__Flow_Step__cRef5"
            },
            "Name": "Assign Round Robin",
            "TracRTC__Data__c": "{\"stepName\":\"Assign Round Robin\",\"hasEmailCheckbox\":true,\"sendEmailNotification\":false,\"stepId\":null,\"startOfTimePeriod\":\"2017-11-08T18:25:47.976Z\",\"sortCriteriaAura\":null,\"sortCriteria\":[],\"ruleCriteriaAura\":null,\"ruleCriteria\":[{\"userEnteredValue\":\"Products Test\",\"selectedSObjectField\":\"Email\",\"selectedSObject\":\"Lead\",\"selectedOperator\":\"equals\",\"currentDate\":null,\"comparison\":\"EQUALS\"}],\"rrItems\":[],\"originalNumberOfDaysInTimePeriod\":7,\"numberOfDaysInTimePeriod\":7,\"nextUserName\":null,\"lastUserName\":null,\"lastRRItemId\":null,\"lastRRIndex\":null,\"endOfTimePeriod\":\"2017-11-15T18:25:47.976Z\"}"
        },
        {
            "attributes": {
                "type": "TracRTC__Flow_Step__c",
                "referenceId": "TracRTC__Flow_Step__cRef6"
            },
            "Name": "Re-Run Salesforce Lead Assignment Rules",
            "TracRTC__Data__c": "{\"stepName\":\"Re-Run Salesforce Lead Assignment Rules\",\"stepId\":null,\"startOfTimePeriod\":null,\"sortCriteriaAura\":null,\"sortCriteria\":[],\"ruleCriteriaAura\":null,\"ruleCriteria\":[],\"rrItems\":null,\"originalNumberOfDaysInTimePeriod\":null,\"numberOfDaysInTimePeriod\":null,\"nextUserName\":null,\"lastUserName\":null,\"lastRRItemId\":null,\"lastRRIndex\":null,\"endOfTimePeriod\":null}"
        }
	]
},
	"TracRTC__Display_Fields__c": {
    "records": [
        {
            "attributes": {
                "type": "TracRTC__Display_Fields__c",
                "referenceId": "TracRTC__Display_Fields__cRef1"
            },
            "Name": "LeadGlobal123",
            "TracRTC__Display_Name__c": "Global Default Settings",
            "TracRTC__Field_1__c": "Name",
            "TracRTC__Field_2__c": "Title",
            "TracRTC__Field_3__c": "Email",
            "TracRTC__Field_4__c": "Phone",
            "TracRTC__Field_5__c": "City",
            "TracRTC__Field_6__c": "LastModifiedDate",
            "TracRTC__SObjectName__c": "Lead",
            "TracRTC__UserOrProfileId__c": null
        },
            {
            "attributes": {
                "type": "TracRTC__Display_Fields__c",
                "referenceId": "TracRTC__Display_Fields__cRef2"
            },
            "Name": "AccountGlobal123",
            "TracRTC__Display_Name__c": "Global Default Settings",
            "TracRTC__Field_1__c": "Name",
            "TracRTC__Field_2__c": "OwnerId",
            "TracRTC__Field_3__c": "BillingCity",
            "TracRTC__Field_4__c": "BillingCountry",
            "TracRTC__Field_5__c": "CreatedById",
            "TracRTC__Field_6__c": "LastModifiedDate",
            "TracRTC__SObjectName__c": "Account",
            "TracRTC__UserOrProfileId__c": null
        },
        {
            "attributes": {
                "type": "TracRTC__Display_Fields__c",
                "referenceId": "TracRTC__Display_Fields__cRef3"
            },
            "Name": "ContactGlobal123",
            "TracRTC__Display_Name__c": "Global Default Settings",
            "TracRTC__Field_1__c": "Name",
            "TracRTC__Field_2__c": "Title",
            "TracRTC__Field_3__c": "Email",
            "TracRTC__Field_4__c": "Phone",
            "TracRTC__Field_5__c": "LastModifiedDate",
            "TracRTC__Field_6__c": null,
            "TracRTC__SObjectName__c": "Contact",
            "TracRTC__UserOrProfileId__c": null
        },
        {
            "attributes": {
                "type": "TracRTC__Display_Fields__c",
                "referenceId": "TracRTC__Display_Fields__cRef4"
            },
            "Name": "OpportunityGlobal123",
            "TracRTC__Display_Name__c": "Global Default Settings",
            "TracRTC__Field_1__c": "Name",
            "TracRTC__Field_2__c": "OwnerId",
            "TracRTC__Field_3__c": "StageName",
            "TracRTC__Field_4__c": "Amount",
            "TracRTC__Field_5__c": "CloseDate",
            "TracRTC__Field_6__c": "NextStep",
            "TracRTC__SObjectName__c": "Opportunity",
            "TracRTC__UserOrProfileId__c": null
        }
    ]
}
}